---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop-web-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Epowei/sock-shop-microservice.git
    targetRevision: HEAD
    path: ./manifest/sock-shop
  destination: 
    server: https://kubernetes.default.svc
    namespace: sock-shop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
